"""add_tenant_id_to_executions

Revision ID: 8cd0de7aa8de
Revises: 978465238af9
Create Date: 2026-06-06 20:38:47.419538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd0de7aa8de'
down_revision: Union[str, Sequence[str], None] = '978465238af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add column as nullable
    op.add_column('workflow_executions', sa.Column('tenant_id', sa.String(length=100), nullable=True))
    
    # 2. Fill existing records with default 'default'
    op.execute("UPDATE workflow_executions SET tenant_id = 'default' WHERE tenant_id IS NULL")
    
    # 3. Apply NOT NULL and create index
    op.alter_column('workflow_executions', 'tenant_id', nullable=False)
    op.create_index(op.f('ix_workflow_executions_tenant_id'), 'workflow_executions', ['tenant_id'], unique=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_executions_tenant_id'), table_name='workflow_executions')
    op.drop_column('workflow_executions', 'tenant_id')
    # ### end Alembic commands ###
