"""add_workflow_version_to_executions

Revision ID: 978465238af9
Revises: b3a96dc818a5
Create Date: 2026-06-06 20:15:28.623726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '978465238af9'
down_revision: Union[str, Sequence[str], None] = 'b3a96dc818a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add column as nullable
    op.add_column('workflow_executions', sa.Column('workflow_version', sa.String(length=50), nullable=True))
    
    # 2. Fill existing records with default '1.0.0'
    op.execute("UPDATE workflow_executions SET workflow_version = '1.0.0' WHERE workflow_version IS NULL")
    
    # 3. Apply NOT NULL constraint
    op.alter_column('workflow_executions', 'workflow_version', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_executions', 'workflow_version')
    # ### end Alembic commands ###
